### ISSUE TITLE
kuberbetes traefik简单应用 | Louis Blog

### ISSUE THREAD

**Issue by oldthreefeng** [oldthreefeng/oldthreefeng.github.io#63]
https://www.fenghong.tech/blog/kubernetes/kubernetes-traefik/#%E5%9F%BA%E6%9C%AC%E8%AF%B4%E6%98%8E 

 本文介绍了使用traefik来暴露kubernetes集群应用。

**Comment by oldthreefeng** [comment]
1. ssl证书创建

```
$ kubectl create secret tls youpenglai-tls --cert=youpenglai.crt --key=youpenglai.key
secret/youpenglai-tls created
```

2.  args 添加secure ep
```
- --entryPoints.websecure.address=:443
```
3. 暴露pod的443端口
```
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
```
4. IngressRoute添加annotions.  
```
annotations:
  traefik.ingress.kubernetes.io/router.entrypoints: websecure
```
